-- @generated by SqlDdlEmitter -- DO NOT EDIT
-- Re-generate: php bin/regenerate (or artisan teleframe:regenerate [--ship])
-- Table: tf_channels  (§2 exact types, extracted from the .tl scheme)
-- Domain: channels  key: global  classified ctors: 2  layer: 227  fillfactor: 90
--
-- Extraction rules (docs/superpowers/plans/2026-09-12-sql-extraction-phase.md):
--   int stays INTEGER (int32; unix dates never timestamptz); long → BIGINT
--   flags → BOOLEAN NOT NULL DEFAULT false (never nullable)
--   string → VARCHAR(n), n = exact Telegram limit (never text)
--   Peer refs → canonical peer long; everything else nests in tl_data JSONB
--   serial key: append-only log — no updated_at, fillfactor 100

CREATE TABLE tf_channels (
    id BIGINT,
    access_hash BIGINT,
    title VARCHAR(128),
    username VARCHAR(32),
    date INTEGER,
    participants_count INTEGER,
    is_broadcast BOOLEAN NOT NULL DEFAULT false,
    is_megagroup BOOLEAN NOT NULL DEFAULT false,
    is_verified BOOLEAN NOT NULL DEFAULT false,
    is_restricted BOOLEAN NOT NULL DEFAULT false,
    is_left BOOLEAN NOT NULL DEFAULT false,
    is_forum BOOLEAN NOT NULL DEFAULT false,
    restriction_reason VARCHAR(255),
    constructor_id INTEGER NOT NULL,
    account_id BIGINT NOT NULL,
    tl_data JSONB NOT NULL,
    PRIMARY KEY (account_id, id)
) WITH (fillfactor = 90);

CREATE INDEX tf_channels_account_id_idx ON tf_channels (account_id);
CREATE INDEX tf_channels_username_partial_idx ON tf_channels (username) WHERE username IS NOT NULL;

COMMENT ON TABLE tf_channels IS 'teleframe mirror: key=global fillfactor=90
; hot UPDATE table — keep autovacuum_vacuum_scale_factor low (per-table),
  leave fillfactor headroom for in-place updates
';
