-- @generated by SqlDdlEmitter -- DO NOT EDIT
-- Re-generate: php bin/regenerate (or artisan teleframe:regenerate [--ship])
-- Table: tf_channel_participants  (§2 exact types, extracted from the .tl scheme)
-- Domain: channel_participants  key: natural  classified ctors: 6  layer: 227  fillfactor: 90
--
-- Extraction rules (docs/superpowers/plans/2026-09-12-sql-extraction-phase.md):
--   int stays INTEGER (int32; unix dates never timestamptz); long → BIGINT
--   flags → BOOLEAN NOT NULL DEFAULT false (never nullable)
--   string → VARCHAR(n), n = exact Telegram limit (never text)
--   Peer refs → canonical peer long; everything else nests in tl_data JSONB
--   serial key: append-only log — no updated_at, fillfactor 100

CREATE TABLE tf_channel_participants (
    channel_id BIGINT,
    user_id BIGINT,
    date INTEGER,
    constructor_id INTEGER NOT NULL,
    account_id BIGINT NOT NULL,
    tl_data JSONB NOT NULL,
    PRIMARY KEY (channel_id, user_id, account_id)
) WITH (fillfactor = 90);

CREATE INDEX tf_channel_participants_account_id_idx ON tf_channel_participants (account_id);

COMMENT ON TABLE tf_channel_participants IS 'teleframe mirror: key=natural fillfactor=90
; hot UPDATE table — keep autovacuum_vacuum_scale_factor low (per-table),
  leave fillfactor headroom for in-place updates
';
