-- @generated by SqlDdlEmitter -- DO NOT EDIT
-- Re-generate: php bin/regenerate (or artisan teleframe:regenerate [--ship])
-- Table: tf_dialogs  (§2 exact types, extracted from the .tl scheme)
-- Domain: dialogs  key: natural  classified ctors: 2  layer: 227  fillfactor: 90
--
-- Extraction rules (docs/superpowers/plans/2026-09-12-sql-extraction-phase.md):
--   int stays INTEGER (int32; unix dates never timestamptz); long → BIGINT
--   flags → BOOLEAN NOT NULL DEFAULT false (never nullable)
--   string → VARCHAR(n), n = exact Telegram limit (never text)
--   Peer refs → canonical peer long; everything else nests in tl_data JSONB
--   serial key: append-only log — no updated_at, fillfactor 100

CREATE TABLE tf_dialogs (
    peer_id BIGINT,
    peer_type VARCHAR(32),
    top_message_id INTEGER,
    unread_count INTEGER,
    unread_mentions INTEGER,
    is_pinned BOOLEAN NOT NULL DEFAULT false,
    pts INTEGER,
    constructor_id INTEGER NOT NULL,
    account_id BIGINT NOT NULL,
    tl_data JSONB NOT NULL,
    PRIMARY KEY (peer_id, account_id)
) WITH (fillfactor = 90);

CREATE INDEX tf_dialogs_account_id_idx ON tf_dialogs (account_id);

COMMENT ON TABLE tf_dialogs IS 'teleframe mirror: key=natural fillfactor=90
; hot UPDATE table — keep autovacuum_vacuum_scale_factor low (per-table),
  leave fillfactor headroom for in-place updates
';
