-- @generated by SqlDdlEmitter -- DO NOT EDIT
-- Re-generate: php bin/regenerate (or artisan teleframe:regenerate [--ship])
-- Table: tf_messages  (§2 exact types, extracted from the .tl scheme)
-- Domain: messages  key: natural  classified ctors: 3  layer: 227  fillfactor: 90
--
-- Extraction rules (docs/superpowers/plans/2026-09-12-sql-extraction-phase.md):
--   int stays INTEGER (int32; unix dates never timestamptz); long → BIGINT
--   flags → BOOLEAN NOT NULL DEFAULT false (never nullable)
--   string → VARCHAR(n), n = exact Telegram limit (never text)
--   Peer refs → canonical peer long; everything else nests in tl_data JSONB
--   serial key: append-only log — no updated_at, fillfactor 100

CREATE TABLE tf_messages (
    peer_id BIGINT,
    message_id INTEGER,
    from_id BIGINT,
    date INTEGER,
    is_out BOOLEAN NOT NULL DEFAULT false,
    is_mentioned BOOLEAN NOT NULL DEFAULT false,
    is_silent BOOLEAN NOT NULL DEFAULT false,
    is_pinned BOOLEAN NOT NULL DEFAULT false,
    message VARCHAR(4096),
    media_type VARCHAR(32),
    reply_to_msg_id INTEGER,
    constructor_id INTEGER NOT NULL,
    account_id BIGINT NOT NULL,
    tl_data JSONB NOT NULL,
    PRIMARY KEY (peer_id, message_id, account_id)
) WITH (fillfactor = 90);

CREATE INDEX tf_messages_peer_id_date_idx ON tf_messages (peer_id, date);
CREATE INDEX tf_messages_from_id_partial_idx ON tf_messages (from_id) WHERE from_id IS NOT NULL;

COMMENT ON TABLE tf_messages IS 'teleframe mirror: key=natural fillfactor=90
; hot UPDATE table — keep autovacuum_vacuum_scale_factor low (per-table),
  leave fillfactor headroom for in-place updates
';
