-- @generated by SqlDdlEmitter -- DO NOT EDIT
-- Re-generate: php bin/regenerate (or artisan teleframe:regenerate [--ship])
-- Table: tf_sticker_sets  (§2 exact types, extracted from the .tl scheme)
-- Domain: sticker_sets  key: global  classified ctors: 1  layer: 227  fillfactor: 90
--
-- Extraction rules (docs/superpowers/plans/2026-09-12-sql-extraction-phase.md):
--   int stays INTEGER (int32; unix dates never timestamptz); long → BIGINT
--   flags → BOOLEAN NOT NULL DEFAULT false (never nullable)
--   string → VARCHAR(n), n = exact Telegram limit (never text)
--   Peer refs → canonical peer long; everything else nests in tl_data JSONB
--   serial key: append-only log — no updated_at, fillfactor 100

CREATE TABLE tf_sticker_sets (
    id BIGINT,
    access_hash BIGINT,
    title VARCHAR(128),
    short_name VARCHAR(64),
    count INTEGER,
    constructor_id INTEGER NOT NULL,
    account_id BIGINT NOT NULL,
    tl_data JSONB NOT NULL,
    PRIMARY KEY (account_id, id)
) WITH (fillfactor = 90);

CREATE INDEX tf_sticker_sets_account_id_idx ON tf_sticker_sets (account_id);

COMMENT ON TABLE tf_sticker_sets IS 'teleframe mirror: key=global fillfactor=90
; hot UPDATE table — keep autovacuum_vacuum_scale_factor low (per-table),
  leave fillfactor headroom for in-place updates
';
