-- @generated by SqlDdlEmitter -- DO NOT EDIT
-- Re-generate: php bin/regenerate (or artisan teleframe:regenerate [--ship])
-- Table: tf_stories  (§2 exact types, extracted from the .tl scheme)
-- Domain: stories  key: natural  classified ctors: 14  layer: 227  fillfactor: 90
--
-- Extraction rules (docs/superpowers/plans/2026-09-12-sql-extraction-phase.md):
--   int stays INTEGER (int32; unix dates never timestamptz); long → BIGINT
--   flags → BOOLEAN NOT NULL DEFAULT false (never nullable)
--   string → VARCHAR(n), n = exact Telegram limit (never text)
--   Peer refs → canonical peer long; everything else nests in tl_data JSONB
--   serial key: append-only log — no updated_at, fillfactor 100

CREATE TABLE tf_stories (
    peer_id BIGINT,
    story_id INTEGER,
    date INTEGER,
    expire_date INTEGER,
    caption VARCHAR(1024),
    constructor_id INTEGER NOT NULL,
    account_id BIGINT NOT NULL,
    tl_data JSONB NOT NULL,
    PRIMARY KEY (peer_id, story_id, account_id)
) WITH (fillfactor = 90);

CREATE INDEX tf_stories_account_id_idx ON tf_stories (account_id);

COMMENT ON TABLE tf_stories IS 'teleframe mirror: key=natural fillfactor=90
; hot UPDATE table — keep autovacuum_vacuum_scale_factor low (per-table),
  leave fillfactor headroom for in-place updates
';
