-- @generated by SqlDdlEmitter -- DO NOT EDIT
-- Re-generate: php bin/regenerate (or artisan teleframe:regenerate [--ship])
-- Table: tf_users  (§2 exact types, extracted from the .tl scheme)
-- Domain: users  key: global  classified ctors: 2  layer: 227  fillfactor: 90
--
-- Extraction rules (docs/superpowers/plans/2026-09-12-sql-extraction-phase.md):
--   int stays INTEGER (int32; unix dates never timestamptz); long → BIGINT
--   flags → BOOLEAN NOT NULL DEFAULT false (never nullable)
--   string → VARCHAR(n), n = exact Telegram limit (never text)
--   Peer refs → canonical peer long; everything else nests in tl_data JSONB
--   serial key: append-only log — no updated_at, fillfactor 100

CREATE TABLE tf_users (
    id BIGINT,
    access_hash BIGINT,
    first_name VARCHAR(64),
    last_name VARCHAR(64),
    username VARCHAR(32),
    phone VARCHAR(16),
    is_bot BOOLEAN NOT NULL DEFAULT false,
    is_self BOOLEAN NOT NULL DEFAULT false,
    is_contact BOOLEAN NOT NULL DEFAULT false,
    is_premium BOOLEAN NOT NULL DEFAULT false,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    status_type VARCHAR(32),
    constructor_id INTEGER NOT NULL,
    account_id BIGINT NOT NULL,
    tl_data JSONB NOT NULL,
    PRIMARY KEY (account_id, id)
) WITH (fillfactor = 90);

CREATE INDEX tf_users_account_id_idx ON tf_users (account_id);
CREATE INDEX tf_users_username_partial_idx ON tf_users (username) WHERE username IS NOT NULL;
CREATE INDEX tf_users_phone_partial_idx ON tf_users (phone) WHERE phone IS NOT NULL;

COMMENT ON TABLE tf_users IS 'teleframe mirror: key=global fillfactor=90
; hot UPDATE table — keep autovacuum_vacuum_scale_factor low (per-table),
  leave fillfactor headroom for in-place updates
';
