-- @generated by SqlDdlEmitter -- DO NOT EDIT
-- Re-generate: php bin/regenerate (or artisan teleframe:regenerate [--ship])
-- Table: tf_updates  (§2 exact types, extracted from the .tl scheme)
-- Domain: updates  key: serial  classified ctors: 168  layer: 227  fillfactor: 100
--
-- Extraction rules (docs/superpowers/plans/2026-09-12-sql-extraction-phase.md):
--   int stays INTEGER (int32; unix dates never timestamptz); long → BIGINT
--   flags → BOOLEAN NOT NULL DEFAULT false (never nullable)
--   string → VARCHAR(n), n = exact Telegram limit (never text)
--   Peer refs → canonical peer long; everything else nests in tl_data JSONB
--   serial key: append-only log — no updated_at, fillfactor 100

CREATE TABLE tf_updates (
    id BIGSERIAL PRIMARY KEY,
    pts INTEGER,
    pts_count INTEGER,
    date INTEGER,
    channel_id BIGINT,
    user_id BIGINT,
    peer_id BIGINT,
    message_id INTEGER,
    constructor_id INTEGER NOT NULL,
    account_id BIGINT NOT NULL,
    tl_data JSONB NOT NULL
) WITH (fillfactor = 100);

CREATE INDEX tf_updates_account_id_idx ON tf_updates (account_id);
CREATE INDEX tf_updates_peer_id_partial_idx ON tf_updates (peer_id) WHERE peer_id IS NOT NULL;

COMMENT ON TABLE tf_updates IS 'teleframe mirror: key=serial fillfactor=100
; append-only log — no UPDATE path, autovacuum at default aggressive settings
';
