-- @generated by SqlDdlEmitter -- DO NOT EDIT
-- Re-generate: php bin/regenerate (or artisan teleframe:regenerate [--ship])
-- Table: tf_wallpapers  (§2 exact types, extracted from the .tl scheme)
-- Domain: wallpapers  key: global  classified ctors: 2  layer: 227  fillfactor: 90
--
-- Extraction rules (docs/superpowers/plans/2026-09-12-sql-extraction-phase.md):
--   int stays INTEGER (int32; unix dates never timestamptz); long → BIGINT
--   flags → BOOLEAN NOT NULL DEFAULT false (never nullable)
--   string → VARCHAR(n), n = exact Telegram limit (never text)
--   Peer refs → canonical peer long; everything else nests in tl_data JSONB
--   serial key: append-only log — no updated_at, fillfactor 100

CREATE TABLE tf_wallpapers (
    id BIGINT,
    access_hash BIGINT,
    slug VARCHAR(255),
    is_pattern BOOLEAN NOT NULL DEFAULT false,
    is_dark BOOLEAN NOT NULL DEFAULT false,
    constructor_id INTEGER NOT NULL,
    account_id BIGINT NOT NULL,
    tl_data JSONB NOT NULL,
    document_id BIGINT,
    PRIMARY KEY (account_id, id)
) WITH (fillfactor = 90);

CREATE INDEX tf_wallpapers_account_id_idx ON tf_wallpapers (account_id);

COMMENT ON TABLE tf_wallpapers IS 'teleframe mirror: key=global fillfactor=90
; hot UPDATE table — keep autovacuum_vacuum_scale_factor low (per-table),
  leave fillfactor headroom for in-place updates
';
