<?php

declare(strict_types=1);

namespace MeRezaRezaei\Teleframe\Schema\Generator\SqlDdl;

use MeRezaRezaei\Teleframe\Schema\Generator\Model\TlConstructor;
use MeRezaRezaei\Teleframe\Schema\Generator\Model\TlScheme;
use MeRezaRezaei\Teleframe\Schema\Generator\Naming;
use RuntimeException;

/**
 * The extraction emitter (plan §6/§8.4): turns the parsed .tl scheme +
 * DomainManifest into one deterministic Postgres DDL file per domain table.
 *
 * The .tl IS the schema here — every field-promoted column is validated at
 * emit time against the domain's classified ctors (Naming::classifyConstructor):
 *   - the field must exist in at least one classified ctor, AND
 *   - its TL type must be promotable by TypeMapper (scalar/flag/peer-long/Bool),
 * else the manifest is rejected. The manifest cannot silently drift from .tl.
 *
 * Output contracts (per plan):
 *   - exact §2 types (int→INTEGER, long→BIGINT, bigInteger never)
 *   - global PK (account_id, id) / natural composite PK / serial BIGSERIAL
 *   - flags → BOOLEAN NOT NULL DEFAULT false, never nullable booleans
 *   - partial indexes WHERE col IS NOT NULL on sparse columns (never full)
 *   - fillfactor per table class; autovacuum guidance as COMMENT, not ALTER
 *   - @generated marker — regenerated, never hand-edited
 */
final class SqlDdlEmitter
{
    /** @return array<string,string> filename (tf_users.sql) => DDL content */
    public function generate(TlScheme $scheme): array
    {
        $out = [];
        foreach (DomainManifest::tables() as $table => $spec) {
            $out[$table . '.sql'] = $this->emitTable($scheme, $table, $spec);
        }
        ksort($out);
        return $out;
    }

    /**
     * @param array{
     *   key: 'global'|'natural'|'serial',
     *   pk?: list<string>,
     *   columns: list<array{col:string, field?:string, sql?:string}>,
     *   partial?: list<string>,
     *   indexes?: list<list<string>>,
     *   fillfactor: int
     * } $spec
     */
    private function emitTable(TlScheme $scheme, string $table, array $spec): string
    {
        $domain = substr($table, 3);
        $ctors = $this->domainConstructors($scheme, $domain);

        $lines = [];
        $lines[] = '-- @generated by SqlDdlEmitter -- DO NOT EDIT';
        $lines[] = '-- Re-generate: php bin/regenerate (or artisan teleframe:regenerate [--ship])';
        $lines[] = "-- Table: {$table}  (§2 exact types, extracted from the .tl scheme)";
        $lines[] = sprintf(
            '-- Domain: %s  key: %s  classified ctors: %d  layer: %d  fillfactor: %d',
            $domain,
            $spec['key'],
            count($ctors),
            $scheme->layer,
            $spec['fillfactor'],
        );
        $lines[] = '--';
        $lines[] = '-- Extraction rules (docs/superpowers/plans/2026-09-12-sql-extraction-phase.md):';
        $lines[] = '--   int stays INTEGER (int32; unix dates never timestamptz); long → BIGINT';
        $lines[] = '--   flags → BOOLEAN NOT NULL DEFAULT false (never nullable)';
        $lines[] = '--   string → VARCHAR(n), n = exact Telegram limit (never text)';
        $lines[] = '--   Peer refs → canonical peer long; everything else nests in tl_data JSONB';
        $lines[] = '--   serial key: append-only log — no updated_at, fillfactor 100';
        $lines[] = "";

        $colLines = [];
        foreach ($spec['columns'] as $col) {
            $colLines[] = '    ' . $this->columnDdl($table, $domain, $ctors, $col);
        }

        $key = $spec['key'];
        if ($key === 'serial') {
            // id BIGSERIAL PRIMARY KEY inline (manifest declares it) — append
            // order = disk order; no table-level PK to duplicate it.
        } elseif (($spec['pk'] ?? []) !== []) {
            $colLines[] = '    PRIMARY KEY (' . implode(', ', $spec['pk']) . ')';
        }

        $lines[] = "CREATE TABLE {$table} (";
        $lines[] = implode(",\n", $colLines);
        $lines[] = sprintf(') WITH (fillfactor = %d);', $spec['fillfactor']);
        $lines[] = "";

        foreach ($spec['indexes'] ?? [] as $cols) {
            $lines[] = $this->indexDdl($table, $cols, null);
        }
        foreach ($spec['partial'] ?? [] as $col) {
            $lines[] = $this->indexDdl($table, [$col], $col);
        }

        $lines[] = "";
        $lines[] = $this->tuningComment($table, $spec);
        $lines[] = "";

        return implode("\n", $lines);
    }

    /**
     * One column's DDL. Derived columns ('sql') are emitted verbatim —
     * tenant/provenance meta is authored once in the manifest. Field-promoted
     * columns are decoded from the .tl through TypeMapper and validated.
     *
     * @param list<TlConstructor> $ctors
     * @param array{col:string, field?:string, sql?:string} $col
     */
    private function columnDdl(
        string $table,
        string $domain,
        array $ctors,
        array $col,
    ): string {
        if (isset($col['sql'])) {
            return $col['col'] . ' ' . $col['sql'];
        }
        $field = $col['field'] ?? $col['col'];
        $type = $this->resolveFieldType($table, $domain, $ctors, $col['col'], $field);
        return $col['col'] . ' ' . $type;
    }

    /**
     * Resolve a .tl field to its promoted SQL type across the domain's
     * classified ctors (stable first-promotable wins). Throws when the field
     * is absent from every classified ctor or when every occurrence is
     * unpromotable (vector/nat/nested-ctor) — the manifest may not drift.
     *
     * @param list<TlConstructor> $ctors
     */
    private function resolveFieldType(
        string $table,
        string $domain,
        array $ctors,
        string $column,
        string $field,
    ): string {
        $found = false;
        foreach ($ctors as $ctor) {
            $param = $ctor->params()[$field] ?? null;
            if ($param === null) {
                continue;
            }
            $found = true;
            $mapped = TypeMapper::map($field, $param);
            if ($mapped !== null) {
                return $mapped[0];
            }
        }
        if (!$found) {
            throw new RuntimeException(sprintf(
                'SqlDdl: column %s.%s <- .tl field "%s": no classified ctor of domain "%s" declares it (manifest drift)',
                $table,
                $column,
                $field,
                $domain,
            ));
        }
        throw new RuntimeException(sprintf(
            'SqlDdl: column %s.%s <- .tl field "%s": present in domain "%s" ctors but never promotable (stays in tl_data)',
            $table,
            $column,
            $field,
            $domain,
        ));
    }

    /**
     * Deterministic (insertion-order) list of ctors classified to the domain.
     *
     * @return list<TlConstructor>
     */
    private function domainConstructors(TlScheme $scheme, string $domain): array
    {
        $ctors = [];
        $seen = [];
        foreach ($scheme->types() as $type) {
            foreach ($type->constructors() as $ctor) {
                $cls = Naming::classifyConstructor($ctor->name, $ctor->resultType);
                if ($cls === null || $cls['domain'] !== $domain || isset($seen[$ctor->name])) {
                    continue;
                }
                $seen[$ctor->name] = true;
                $ctors[] = $ctor;
            }
        }
        return $ctors;
    }

    /** @param list<string> $cols @param string|null $partial */
    private function indexDdl(string $table, array $cols, ?string $partial): string
    {
        $name = $table . '_' . implode('_', $cols) . ($partial !== null ? '_partial' : '') . '_idx';
        $on = 'CREATE INDEX ' . $name . ' ON ' . $table . ' (' . implode(', ', $cols) . ')';
        return $partial !== null ? $on . ' WHERE ' . $partial . ' IS NOT NULL;' : $on . ';';
    }

    /**
     * Per-table storage guidance ships as COMMENT (plan §5.8) so the DDL
     * stays a pure contract — no runtime ALTER side-effects on migration.
     *
     * @param array{
     *   key: 'global'|'natural'|'serial',
     *   pk?: list<string>,
     *   columns: list<array{col:string, field?:string, sql?:string}>,
     *   partial?: list<string>,
     *   indexes?: list<list<string>>,
     *   fillfactor: int
     * } $spec
     */
    private function tuningComment(string $table, array $spec): string
    {
        $lines = [];
        $lines[] = "COMMENT ON TABLE {$table} IS 'teleframe mirror: key={$spec['key']} fillfactor={$spec['fillfactor']}";
        if ($spec['key'] === 'serial') {
            $lines[] = '; append-only log — no UPDATE path, autovacuum at default aggressive settings';
        } else {
            $lines[] = '; hot UPDATE table — keep autovacuum_vacuum_scale_factor low (per-table),';
            $lines[] = '  leave fillfactor headroom for in-place updates';
        }
        $lines[] = "';";
        return implode("\n", $lines);
    }
}